Pogakco/FE

- package-lock.json
- package.json
- src/App.tsx
- src/components/footer/Footer.tsx
- src/components/header/Header.tsx
- src/components/inputField/InputField.tsx
- src/components/layout/Layout.tsx
- src/components/profile/Profile.tsx
- src/models/auth.model.ts
- src/pages/UserCheckPassword.1.tsx
- src/pages/UserLogin.tsx
- src/pages/UserProfile.tsx
- src/pages/UserSignup.tsx
- 로그인, 회원가입, 비밀번호 확인, 프로필 수정 페이지 제작
- 유효성 검사 로직
- 모듈 분리는 나중에 작업하겠습니다.
closed #14
> Feat: auth UI 제작

- src/api/apiClient.ts
- src/constants/socket.ts
- vite.config.ts
- 소켓 io 프록시 설정 추가
- vite config 소켓 proxy 설정 추가
- 기존 소켓 연결 url 변경
closed #36
> Feat : socket.io 프록시 설정 추가

- src/components/cards/TimerDescriptCard.tsx
- src/models/room.model.ts
- src/pages/RoomDetail.tsx
> Fix : 빌드 오류 해결

- src/components/footer/Footer.tsx
- src/components/header/Header.tsx
- 로고 이미지 파일을 절대경로에서 상대경로로 변경
- 운영 환경에서 사진의 경로를 못찾는 문제 해결
closed #54
> Fix: 로고 이미지 파일을 상대 경로로 변경

- src/api/auth.api.ts
- src/components/errorBoundary/FallbackUI.tsx
- src/components/header/Header.tsx
- src/components/user/userProfile/UserImage.tsx
- src/hooks/useAuth.ts
- src/models/auth.model.ts
- src/pages/UserCheckPassword.1.tsx
- src/pages/UserProfile.tsx
- 비밀번호 확인 API 연결
- 프로필 수정하기 연결
closed #53
> Feat: 비밀번호 확인, 프로필 수정 API

- src/hooks/queries/useFetchRooms.ts
- src/pages/Main/Main.tsx
- roomsAPI 반복 요청 수정
- useEffect로 상태 변경을 감지하는 기존 로직에서 tanstackQuery 키 값에 함수 인자를 넣어 인자 값이 변경될 때 동작하도록 수정하였습니다.
closed #66
> Fix : roomsAPI 반복 요청 수정

- package-lock.json
- package.json
- src/components/errorBoundary/FallbackUI.tsx
- src/components/roomDetail/RoomButtons.tsx
- src/main.tsx
- 나가기 UI 변경
- 리액트 devtools 설치
closed #73
> Feat: 나가기 UI 변경

- src/components/roomDetail/RoomButtons.tsx
- src/constants/socket.ts
- src/hooks/queries/useFetchRoomDetail.ts
- src/hooks/useEmitSocket.ts
- src/hooks/useTimer.ts
- src/pages/RoomDetail.tsx
> Feat : 방 삭제 소켓 연동

- src/components/inputField/InputField.tsx
- src/components/modal/ModalStyle.ts
- src/components/modal/modalContents/ModalRoomCreate.tsx
- src/components/slider/SliderStyle.ts
- src/main.tsx
- src/style/scrollbar.css
- src/utils/timerUi.ts
- 방 생성 모달에 defaultvalue 지정
- 스크롤바 디자인
- 모달 x 버튼 수정
- 슬라이더 버튼
-  InputField 라벨 위치를 아래로 조정
closed #87
> Design: 배너,모달창 디자인 등 변경

- src/api/feedback.api.ts
- src/components/footer/FeedBack.tsx
- src/components/footer/Footer.tsx
- src/hooks/mutations/useFeedback.ts
> Feat: 피드백 api 연결

- src/components/drawer/drawerContents/UserListBox.tsx
- Active 상태인 경우 불꽃 이모지가 출력
- 뽀모도로 사이클을 1회 돈 후, Active 여부에 따라 불꽃 이미지를 출력하도록 하였습니다.
- <img width="225" alt="image" src="https://github.com/user-attachments/assets/693d823c-aebc-45f7-a039-69505c829e8b">
closed #103
> Feat : Active 상태인 경우 불꽃 이모지 출력

- src/pages/RoomDetail.tsx
- 관전 모드일 때 방 디테일 페이지에 표시
closed #101
> Design/different mode UI

- src/components/drawer/drawerContents/RoomActiveUser.tsx
- 참여인원 리스트 길이 버그 수정
closed #111
> Fix : 참여인원 리스트 길이 수정

- src/components/modal/modalContents/ModalRoomCreate.tsx
- src/style/scrollbar.css
- 방 생성 후 바로 방을 참가하였을 때 방 나가기 버튼이 1개만 나오는 오류 해결(긴급)
- 전체 화면의 스크롤바를 auto로 지정하여 한비님이 얘기한 헤더가 화면 끝까지 닿지 않는 오류 처리
closed #113
> Fix: 방 생성 후 바로 방을 참가하였을 때 방 나가기 버튼이 1개만 나오는 오류 해결

- src/constants/inputField.tsx
- src/constants/regex.ts
- src/utils/timerUi.ts
- 방 생성 유효성 검사 수정
- 방 생성 유효성 검사 뽀모도로 사이클 1-4회로 수정, 유효성 및 정규식 수정
- isRunning 상태를 동기화인 경우에만 받도록 수정
closed #117
> Fix : isRunning 수정 및 방 생성 유효성 검사 수정

- src/components/footer/Footer.tsx
- src/constants/inputField.tsx
- 유효성 검사 오류 수정 및 노션 연결
closed #122
> 유효성 검사 오류 수정 및 노션 연결

- package-lock.json
- package.json
- src/components/layout/Layout.tsx
- src/hooks/useAnalytics.ts
- 방문자 수 조회 등의 정보를 얻기 위해 Google Analytics를 적용 했습니다.
- `npm install`을 해주세요.
- 최신 `.env` 파일을 받아와서 프로젝트에 추가해 주세요.
closed #120
> Feat: Google Analytics 적용 

- src/constants/socket.ts
- src/hooks/useEmitSocket.ts
- 버그 수정
- 이전 구현 방식인 servertime emit 코드가 지워지지 않고 매 초마다 호출하고 있어 해당 부분을 제거하였습니다.
> Fix : 미구현된 servertime emit 코드로 인한 불필요한 소켓 통신 버그 수정

- src/hooks/useTimer.ts
- src/utils/getTimerTime.ts
- src/utils/serverTime.ts
- 버그 수정
- 운영 서버에서 디버깅 콘솔 삭제, 만악의 근원 ServerTime 클래스의 getSyncTime 메서드 삭제
closed #131
> 디버깅 콘솔 삭제, getSyncTime 삭제

- src/components/tooltip/Tooltip.tsx
- 최근 로그인한 계정 툴팁에 에니메이션을 추가하여, 유저의 시선을 이동시키도록 유도하였습니다.
- 사용자는 선택지가 줄어들어 빠른 소셜 로그인을 할 수 있습니다.
closed #136
> Feat: 최근 로그인한 계정 툴팁에 에니메이션 추가

- declarations.d.ts
- global.d.ts
- src/components/errorBoundary/FallbackUI.tsx
- src/pages/KaKaoCallback.tsx
- 사용하지 않는 error 변수 삭제
- lint 통과하기 위해 사용하지 않는 변수를 삭제
closed #139
> Fix: 사용하지 않는 error 변수 삭제
